## Exploring the Data and the Resolution

This notebook looks at two things: the raw data as the agencies published it, and what Senzing concluded about it.  We will move back and forth between the two, because the point of entity resolution only becomes clear when you can see what the records looked like before it ran.

As a reminder, the ER has already been done as part of notebook 01 and provided to you in a pre-populated database.  So after running notebook 00, you can dive back in here.

In [11]:
import os, json, grpc, pandas as pd
from pathlib import Path
from senzing import SzEngineFlags as F
from senzing_grpc import SzAbstractFactoryGrpc
from sqlalchemy import create_engine
from pprint import pprint
from IPython.display import JSON

channel = grpc.insecure_channel(
    f"{os.getenv('SENZING_GRPC_HOST', 'resolver')}:8261",
    options=[('grpc.max_receive_message_length', 200 * 1024 * 1024)])
grpc.channel_ready_future(channel).result(timeout=20)

sz = SzAbstractFactoryGrpc(channel)
engine = sz.create_engine()
print("✅ connected to the resolver")

# Both connections belong here, before any cell queries either one.
db = create_engine(
    f"postgresql+psycopg2://{os.getenv('POSTGRES_USER', 'postgres')}:"
    f"{os.getenv('POSTGRES_PASSWORD', 'workshop')}@"
    f"{os.getenv('POSTGRES_HOST', 'postgres')}:5432/"
    f"{os.getenv('POSTGRES_DB', 'erkg')}")
print("✅ connected to the database")

✅ connected to the resolver
✅ connected to the database

## What We Are Working With

As described in the lecture and in notebook 01, we are working with several publicly-available files from a variety of agencies within California, with three different delimiters between them.  However, the three state filing files use `*|*`, which the Python `csv` module cannot handle because it only accepts a single character.  So here we will just explore what is in those files.

In [2]:
DATA = Path('/workspace/data/filtered')
DELIM = {'.tsv': 'tab', '.csv': 'comma'}
PIPE = {'Agents.csv', 'Filings.csv', 'Principals.csv'}

for f in sorted(DATA.iterdir()):
    rows = sum(1 for _ in f.open(encoding='utf-8-sig', errors='replace')) - 1
    size = f.stat().st_size
    human = f"{size/1e6:.1f} MB" if size >= 1e6 else f"{size/1e3:.0f} KB"
    sep = 'pipe (*|*)' if f.name in PIPE else DELIM[f.suffix]
    print(f"  {f.name:<52} {rows:>7,} rows  {human:>8}  {sep}")

  Agents.csv                                             7,421 rows    1.2 MB  pipe (*|*)
  CA-ABC-LicenseReport-nonretail.csv                        19 rows      3 KB  comma
  CA-ABC-LicenseReport-retail.csv                          201 rows     30 KB  comma
  Filings.csv                                            7,801 rows    2.9 MB  pipe (*|*)
  Principals.csv                                         5,701 rows    858 KB  pipe (*|*)
  burlingame.tsv                                         4,781 rows    448 KB  tab
  master-list-of-ca-licensed-contractors-personnel.csv  10,215 rows    2.4 MB  comma
  master-list-of-ca-licensed-contractors.csv             3,274 rows    1.1 MB  comma

## The Raw Sources

The next few cells open each file so you can see the columns as published.  Notice that no two agencies describe a business the same way, and that none of them share an identifier.  And this, in and of itself, is an interesting thing because, as we will see below, Senzing doesn't really care.

In [3]:
burlingame = pd.read_csv(DATA/'burlingame.tsv', sep='\t', dtype=str)
burlingame.head()

,Account #,Business Name,Start Date,Expire Date,Address
0,20509315,101 MOBILITY,7/1/2025,6/30/2027,"1731 ADRIAN RD STE 9, BURLINGAME, CA 94010-2109"
1,20510000,"1120 BROADWAY, LLC",10/28/2024,6/30/2027,"1120 BROADWAY, BURLINGAME, CA 94010-3422"
2,20501122,1199 HOWARD LLC,7/1/2010,6/30/2027,"330 PRIMROSE RD # 606, BURLINGAME, CA 94010-4032"
3,20501289,1202 HAIR STUDIO (GINA A GIUSTI),11/5/2010,6/30/2026,"1202 CAPUCHINO AVE, BURLINGAME, CA 94010-3404"
4,20504964,1202 HAIR STUDIO - HAIR BY MARINA,2/1/2022,6/30/2027,"1202 CAPUCHINO, BURLINGAME, CA 94010"

In [4]:
agents = pd.read_csv(DATA/'Agents.csv', sep=r'\*\|\*', engine='python', dtype=str)
agents.head()

,ENTITY_NAME,ENTITY_NUM,ORG_NAME,FIRST_NAME,MIDDLE_NAME,LAST_NAME,PHYSICAL_ADDRESS1,PHYSICAL_ADDRESS2,PHYSICAL_ADDRESS3,PHYSICAL_CITY,PHYSICAL_STATE,PHYSICAL_COUNTRY,PHYSICAL_POSTAL_CODE,AGENT_TYPE
0,Busse Manufacturing LLC,B20260056953,NaN,Richard,Hugh,Busse,610 TRAYER AVE,NaN,NaN,GLENDORA,CA,UNITED STATES,91741,Individual Agent
1,Brilliant Day Consulting LLC,B20260116027,NaN,Mingrui,NaN,Xiong,701 S WOODS AVE,NaN,NaN,FULLERTON,CA,UNITED STATES,92832,Individual Agent
2,FEROCIOUS PLUMBING INC,B20260200247,NaN,ANGEL,NaN,OCEGUEDA,3360 SOUTHERN AVE,NaN,NaN,SOUTH GATE,CA,UNITED STATES,90280,Individual Agent
3,"Get Hired, Properly! LLC",B20260116314,NaN,Mingrui,NaN,Xiong,701 S WOODS AVE,NaN,NaN,FULLERTON,CA,UNITED STATES,92832,Individual Agent
4,Guardian Traffic Control LLC,B20260185536,NaN,Amanda,NaN,Landin,3755 WILDRYE DR,NaN,NaN,SAN BERNARDINO,CA,UNITED STATES,92407,Individual Agent

### Here we are going to look at one specific contractor that I noticed appeared many times...

In [5]:
contractors = pd.read_csv(DATA/'master-list-of-ca-licensed-contractors.csv', dtype=str)

desilva = contractors[contractors.BusinessName.str.contains('DESILVA', case=False, na=False)]
desilva.head(10)

,LicenseNo,LastUpdate,BusinessName,BUS-NAME-2,FullBusinessName,MailingAddress,City,State,County,ZIPCode,...,DBSuretyCompany,DBNumber,DBEffectiveDate,DBCancellationDate,DBAmount,DateRequired,DiscpCaseRegion,DBBondReason,DBCaseNo,NAME-TP-2
600,1078219,04/27/2026,DESILVA GATES CONSTRUCTION LLC,NaN,NaN,11555 DUBLIN BOULEVARD,DUBLIN,CA,Alameda,94568,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
685,1087418,04/07/2026,DESILVA GATES - PACIFIC STATES A JOINT VENTURE,NaN,NaN,11555 DUBLIN BLVD,DUBLIN,CA,Alameda,94568,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
739,1093103,06/03/2026,DESILVA GATES CONSTRUCTION LLC - MCM A JOINT V...,NaN,NaN,11555 DUBLIN BLVD,DUBLIN,CA,Alameda,94568,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
796,1099346,04/07/2026,DESILVAGATES CONSTRUCTION - VANGUARD A JOINT V...,NaN,NaN,11555 DUBLIN BLVD,DUBLIN,CA,Alameda,94568,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
836,1103207,04/07/2026,DESILVA GATES-VIKING A JOINT VENTURE,NaN,NaN,11555 DUBLIN BLVD,DUBLIN,CA,Alameda,94568,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1042,1125855,07/29/2026,DESILVA GATES - GHILOTTI A JOINT VENTURE,NaN,NaN,11555 DUBLIN BLVD,DUBLIN,CA,Alameda,94568,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1358,1156955,06/22/2026,DESILVA GATES - ANVIL BUILDERS A JOINT VENTURE,NaN,NaN,11555 DUBLIN BLVD,DUBLIN,CA,Alameda,94568,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### And here we are going to look at one specific businesss that appears a few times with two license types...

In [6]:
abc = pd.read_csv(DATA/'CA-ABC-LicenseReport-retail.csv', dtype=str)
abc[abc['Business Name'].str.contains('TOPGOLF', na=False)].head()

,License Number,Status,License Type,Orig. Iss. Date,Expir. Date,Primary Owner,Premises Addr.,Business Name,Geo Code
169,657740,ACTIVE,47,11/19/2024,10/31/2026,"TOPGOLF USA BURLINGAME, LLC","258 ANZA BLVD,BURLINGAME, CA 94010-1939Census...",TOPGOLF,4103
170,657740,ACTIVE,68,11/19/2024,10/31/2026,"TOPGOLF USA BURLINGAME, LLC","258 ANZA BLVD,BURLINGAME, CA 94010-1939Census...",TOPGOLF,4103

In [7]:
burlingame[burlingame['Business Name'].str.contains('TOPGOLF', na=False)].head()

,Account #,Business Name,Start Date,Expire Date,Address
4377,20508711,TOPGOLF,12/13/2024,6/30/2027,"258 N ANZA BLVD, BURLINGAME, CA 94010-1939"

## A fun little geo problem

Notice that the above two have addresses only separated by one letter (Anza vs. N Anza).  But there is no shared identifier between these two.

But now let's look at just the numbers we are dealing with.  Notice that this just looks at exact duplicates in the data.  However, the problem is that exact-match deduplication only catches identical strings.  Everything above such as the missing space, the missing N, the joint ventures, the LLC suffix just slips straight through.

In [8]:
print(f"Burlingame business licences: {len(burlingame):,}")
print(f"Distinct business names:      {burlingame['Business Name'].nunique():,}")
print(f"Contractor licences:          {len(contractors):,}")
print(f"Distinct business names:      {contractors.BusinessName.nunique():,}")
print(f"Distinct phone numbers:       {contractors.BusinessPhone.nunique():,}")

Burlingame business licences: 4,781
Distinct business names:      4,740
Contractor licences:          3,274
Distinct business names:      3,058
Distinct phone numbers:       3,088

## From Raw Row to Senzing Record

Senzing does not store your rows as you gave them.  It parses each one into features, which are the individual names, addresses and phone numbers it can compare against other records.  This cell shows the same business before and after that mapping.

In [9]:
# The raw row from the city file
raw = burlingame[burlingame['Business Name'] == 'TOPGOLF'].iloc[0]
print("RAW ROW:")
print(raw.to_string(), "\n")

# The same row, mapped into Senzing's format and stored
stored = json.loads(engine.get_record('BURLINGAME', '20508711'))
print("AS STORED IN SENZING:")
print(json.dumps(stored['JSON_DATA'], indent=2))

RAW ROW:
Account #                                          20508711
Business Name                                       TOPGOLF
Start Date                                       12/13/2024
Expire Date                                       6/30/2027
Address          258 N ANZA BLVD, BURLINGAME, CA 94010-1939

AS STORED IN SENZING:
{
  "DATA_SOURCE": "BURLINGAME",
  "RECORD_ID": "20508711",
  "FEATURES": [
    {
      "RECORD_TYPE": "ORGANIZATION"
    },
    {
      "NAME_ORG": "TOPGOLF"
    },
    {
      "ADDR_TYPE": "BUSINESS",
      "ADDR_FULL": "258 N ANZA BLVD, BURLINGAME, CA 94010-1939"
    }
  ],
  "LICENSE_START_DATE": "12/13/2024",
  "LICENSE_EXPIRE_DATE": "6/30/2027"
}

## What Senzing Built

Loading 39,413 records produced several tables.  The one to pay attention to is `lib_feat`, which holds every feature Senzing extracted, because the comparison happens between features and not between rows.

In [12]:
tables = pd.read_sql("""
    SELECT 'dsrc_record'         AS table_name, count(*) FROM dsrc_record
    UNION ALL SELECT 'lib_feat',            count(*) FROM lib_feat
    UNION ALL SELECT 'obs_ent',             count(*) FROM obs_ent
    UNION ALL SELECT 'res_ent',             count(*) FROM res_ent
    UNION ALL SELECT 'res_relate',          count(*) FROM res_relate
    UNION ALL SELECT 'workshop.entity_geo', count(*) FROM workshop.entity_geo
    ORDER BY 2 DESC
""", db)
print(tables.to_string(index=False))

         table_name  count
           lib_feat 498992
        dsrc_record  39413
            obs_ent  33906
            res_ent  31339
         res_relate  11822
workshop.entity_geo   2482

## What is in these tables

Most were created by Senzing but we created the `workshop.entity_geo` in notebook 01 to contain the geocodes.

          table_name   count
            lib_feat  498992     <- every name, address, phone it extracted
         dsrc_record   39413     <- your records, kept verbatim
             obs_ent   33906
             res_ent   31339     <- the entities it concluded exist
          res_relate   11822     <- entities that are related but not the same
          entity_geo    2482     <- coordinates we added afterwards

## Records In, Entities Out

This is where the rubber meets the road.  Given a set of records, how many were found to be of the same entity?  How many of them were related but not the same?

In [13]:
records  = pd.read_sql("SELECT count(*) c FROM dsrc_record", db).c[0]
entities = pd.read_sql("SELECT count(*) c FROM res_ent", db).c[0]
related  = pd.read_sql("SELECT count(*) c FROM res_relate", db).c[0]

print(f"records in:       {records:,}")
print(f"entities out:     {entities:,}")
print(f"records merged:   {records - entities:,}")
print(f"related pairs:    {related:,}")

records in:       39,413
entities out:     31,339
records merged:   8,074
related pairs:    11,822

## Where the Records Came From

Senzing stores a numeric `dsrc_id` rather than the data source name, so we read the current configuration to get the labels back.  So if you were to explore the number of rows in each of the datasets, this should match (minus 1 to account for the header of the file).

In [14]:
config = sz.create_configmanager()
cfg = config.create_config_from_config_id(config.get_default_config_id())
names = {d['DSRC_ID']: d['DSRC_CODE']
         for d in json.loads(cfg.get_data_source_registry())['DATA_SOURCES']}
counts = pd.read_sql("SELECT dsrc_id, count(*) AS records FROM dsrc_record "
                     "GROUP BY 1 ORDER BY 2 DESC", db)

counts['data_source'] = counts.dsrc_id.map(names)
print(counts[['data_source', 'records']].to_string(index=False))
print(f"\ntotal: {counts.records.sum():,} records")

            data_source  records
CA-CONTRACTOR-PERSONNEL    10215
         CA-SOS-FILINGS     7801
          CA-SOS-AGENTS     7421
      CA-SOS-PRINCIPALS     5701
             BURLINGAME     4781
         CA-CONTRACTORS     3274
             ABC-RETAIL      201
          ABC-NONRETAIL       19

total: 39,413 records

## One Entity, Several Records

Let's now take a look at a single entity.  Here, we provide a Senzing record ID number and get back all of the data sources that are part of that record, along with their record ID numbers.  We also see the entity ID number, which is a unique ID assigned by Senzing.

In [15]:
entity = json.loads(
    engine.get_entity_by_record_id('BURLINGAME', '20508711'))['RESOLVED_ENTITY']

print(f"entity {entity['ENTITY_ID']}: {entity['ENTITY_NAME']}\n")
for r in entity['RECORDS']:
    print(f"  {r['DATA_SOURCE']:<16} {r['RECORD_ID']}")

entity 4372: TOPGOLF

  BURLINGAME       20508711
  ABC-RETAIL       657740-47
  ABC-RETAIL       657740-68

## The Features Behind the Entity

The following shows all of the features associated with that ID, even if they disagree...

In [16]:
for family, values in entity['FEATURES'].items():
    print(f"{family}:")
    for v in values:
        print(f"    {v['FEAT_DESC']}")

ADDRESS:
    258 N ANZA BLVD, BURLINGAME, CA 94010-1939
NAME:
    TOPGOLF
RECORD_TYPE:
    ORGANIZATION

## Preventing this all from being a proverbial black box

In some settings, particularly those that are legally based, it is important to be able to "show your work."  You have to be able to state how records were collapsed into a single entity.  This is what the `how` function in the SDK does for you.

In this case, we see the match key of `+NAME+ADDRESS`, meaning that in this solitary step the records were merged because they matched on both name and address.  However, in more complicated cases (as we will see shortly) there can be many steps shown and many other tags.  In general though, `+` indicates an attribute that was matched upon while `-` indicates where two records disagree.

In [17]:
how = json.loads(engine.how_entity_by_entity_id(
    entity['ENTITY_ID'], flags=F.SZ_HOW_ENTITY_DEFAULT_FLAGS))

for step in how['HOW_RESULTS']['RESOLUTION_STEPS']:
    info = step['MATCH_INFO']
    print(f"step {step['STEP']}: {info['MATCH_KEY']}   (rule {info['ERRULE_CODE']})")

step 1: +NAME+ADDRESS   (rule CNAME_CFF_CEXCL)

## Searching

`search_by_attributes` takes the same attributes you would load as a record and tells you which existing entities it would match, without storing anything.  The match key tells you which features agreed.

In [18]:
results = json.loads(engine.search_by_attributes(
    json.dumps({'NAME_ORG': 'TOPGOLF', 'ADDR_CITY': 'BURLINGAME'})))

for hit in results['RESOLVED_ENTITIES']:
    e = hit['ENTITY']['RESOLVED_ENTITY']
    print(f"{e['ENTITY_NAME']}  (entity {e['ENTITY_ID']})  match: {hit['MATCH_INFO']['MATCH_KEY']}")

TOPGOLF  (entity 4372)  match: +NAME

## Related, But Not Merged

Senzing publishes two different kinds of conclusions.  The obvious one is that it tells you which records it merged into one entity, as we saw above.  However, it is also able to tell you which entities it believes are connected but deliberately kept apart.  

You can think of this like two people who live together, such as spouses.  They might have very different names but the same address.  So we want our ER to not say these are the same people while also surfacing that they might be related.

The second kind is what we will build the knowledge graph from later.

In [19]:
full = json.loads(engine.get_entity_by_record_id(
    'BURLINGAME', '20509774', flags=F.SZ_ENTITY_DEFAULT_FLAGS))

print(f"{full['RESOLVED_ENTITY']['ENTITY_NAME']} is related to:\n")
for r in full['RELATED_ENTITIES'][:6]:
    print(f"  {r['ENTITY_NAME'][:36]:<36} {r['MATCH_LEVEL_CODE']}  {r['MATCH_KEY']}")

TOLENTINO CONSTRUCTION & RESTORATION INC is related to:

  REPUBLIC REGISTERED AGENT INC        POSSIBLY_RELATED  +ADDRESS
  PACIFIC OPERATIONAL LLC              POSSIBLY_RELATED  +ADDRESS
  GOLDEN TERRA GROUP LLC               POSSIBLY_RELATED  +ADDRESS
  DIABLO VALLEY CONSTRUCTION INC       POSSIBLY_RELATED  +ADDRESS
  OW BUILDERS LLC                      POSSIBLY_RELATED  +ADDRESS
  D&G GARDENING LLC                    POSSIBLY_RELATED  +ADDRESS

### Here is another biggie with that.  And if you think about what a registered agent does, this makes sense.

In [20]:
hub = json.loads(
    engine.get_entity_by_record_id('CA-SOS-AGENTS', 'B20260301695'))['RESOLVED_ENTITY']

print(f"{hub['ENTITY_NAME']}")
print(f"  {len(hub['RECORDS'])} records")
print(f"  {len(hub['FEATURES']['NAME'])} distinct name, {len(hub['FEATURES']['ADDRESS'])} distinct address")

NORTHWEST REGISTERED AGENT INC
  585 records
  1 distinct name, 1 distinct address

## The Match Keys Across the Whole Dataset

Exporting every entity lets us count which features actually drove resolution.  A match key beginning with `+NAME` means the names agreed, `+ADDRESS` means the addresses did, and so on.  So let's get some counts on what type of matches we have in this data.

(This will take several seconds to run.)

In [21]:
rows = []
handle = engine.export_json_entity_report(F.SZ_EXPORT_DEFAULT_FLAGS)
try:
    while (line := engine.fetch_next(handle)):
        e = json.loads(line)['RESOLVED_ENTITY']
        for r in e.get('RECORDS', []):
            rows.append({'entity_id': e['ENTITY_ID'],
                         'data_source': r['DATA_SOURCE'],
                         'match_key': r.get('MATCH_KEY', '')})
finally:
    engine.close_export_report(handle)

df = pd.DataFrame(rows)
print(f"{len(df):,} records -> {df.entity_id.nunique():,} entities")
print(f"\ntop match keys:\n{df[df.match_key != ''].match_key.value_counts().head(10).to_string()}")

39,413 records -> 31,339 entities

top match keys:
match_key
+EXACTLY_SAME                      4192
+NAME+ADDRESS                      3747
+NAME+ADDRESS+REGISTRATION_DATE      61
+NAME+ADDRESS+PHONE                  44
+ADDRESS+PHONE+LIKELY_NAME           13
+NAME+REGISTRATION_DATE               8
+NAME+PHONE                           7

## Adding Location

`workshop.entity_geo` is the table notebook 01 built, holding a placekey and coordinates for each entity we could geocode.  Note that an entity can have more than one row, because it can have more than one address on file.

In [22]:
geo = pd.read_sql("""
    SELECT street, city, placekey, latitude, longitude
    FROM workshop.entity_geo WHERE entity_id = %(eid)s
""", db, params={'eid': entity['ENTITY_ID']})

print(geo.to_string(index=False))

shared = pd.read_sql("""
    SELECT placekey, count(DISTINCT entity_id) AS businesses, min(street) AS address
    FROM workshop.entity_geo GROUP BY placekey
    HAVING count(DISTINCT entity_id) > 1 ORDER BY 2 DESC LIMIT 5
""", db)

print(f"\nbuildings with several businesses:\n{shared.to_string(index=False)}")

         street       city               placekey  latitude   longitude
258 N ANZA BLVD BURLINGAME 0bfl7ardgt@5vg-7y5-2ff 37.590386 -122.352376
  258 ANZA BLVD BURLINGAME 0bfl7ardgt@5vg-7y5-2ff 37.590386 -122.352376

buildings with several businesses:
              placekey  businesses                address
       226@5vg-7y3-b8v          87 533 AIRPORT BLVD # 400
0n4srtfwuu@5vg-7xz-3kf          62            PO BOX 1032
       22k@5vg-7y3-4jv          45     850 BURLINGAME AVE
       22c@5vg-7xx-qvf           9    1410 BURLINGAME AVE
       25x@5vg-7xx-sqz           9 345 LORTON AVE STE 306

## A Harder Case

As noted above, I manually observed several records for DESILVA.  In this case, there are 13 records across two agencies, under several different names.  A `GROUP BY` on business name would have reported thirteen separate companies.  Here we see multiple different names, a single address, and a few phone numbers.

In [23]:
e = json.loads(engine.get_entity_by_record_id(
    'CA-CONTRACTORS', '1087418', flags=F.SZ_ENTITY_DEFAULT_FLAGS))['RESOLVED_ENTITY']

print(f"entity {e['ENTITY_ID']}: {e['ENTITY_NAME']}  ({len(e['RECORDS'])} records)\n")
print("NAMES Senzing decided all belong to this one company:")
for n in e['FEATURES']['NAME']:
    print(f"   {n['FEAT_DESC']}")
print("\nADDRESS:")
for a in e['FEATURES']['ADDRESS']:
    print(f"   {a['FEAT_DESC']}")
print("\nPHONES:")
for p in e['FEATURES']['PHONE']:
    print(f"   {p['FEAT_DESC']}")

entity 1354: DESILVA GATES CONSTRUCTION LLC  (13 records)

NAMES Senzing decided all belong to this one company:
   DE SILVA GATES CONSTRUCTION - MYERS A JOINT VENTURE
   DE SILVA GATES CONSTRUCTION LP
   DESILVA GATES - ANVIL BUILDERS A JOINT VENTURE
   DESILVA GATES - GHILOTTI A JOINT VENTURE
   DESILVA GATES - PACIFIC STATES A JOINT VENTURE
   DESILVA GATES CONSTRUCTION LLC
   DESILVA GATES CONSTRUCTION LLC - MCM A JOINT VENTURE
   PACFIC STATES-TYRRELL A JOINT VENTURE
   PACIFIC STATES - IO ENVIRINMENTAL A JOINT VENTURE
   PACIFIC STATES - SUKUT A JOINT VENTURE

ADDRESS:
   11555 DUBLIN BLVD, DUBLIN, CA 94568-2854

PHONES:
   (925) 361 1533
   (925) 803 4277
   (925) 829 9220

### And now HOW has a much harder job to do...

In [24]:
how = json.loads(engine.how_entity_by_entity_id(
    e['ENTITY_ID'], flags=F.SZ_HOW_ENTITY_DEFAULT_FLAGS))

for step in how['HOW_RESULTS']['RESOLUTION_STEPS']:
    print(f"step {step['STEP']}: {step['MATCH_INFO']['MATCH_KEY']}")

step 1: +NAME+ADDRESS
step 2: +LIKELY_NAME+ADDRESS+PHONE
step 3: +NAME+ADDRESS
step 4: +NAME+ADDRESS
step 5: +LIKELY_NAME+ADDRESS+PHONE
step 6: +LIKELY_NAME+ADDRESS+PHONE
step 7: +NAME+ADDRESS+PHONE
step 8: +LIKELY_NAME+ADDRESS+PHONE
step 9: +LIKELY_NAME+ADDRESS+PHONE
step 10: +LIKELY_NAME+ADDRESS+PHONE
step 11: +LIKELY_NAME+ADDRESS+PHONE
step 12: +LIKELY_NAME+ADDRESS+PHONE

## Another example

Here we have a case where the names match completely but there complete mismatch across the addresses.

So why do you think these entities were merged?

In [25]:
briten = json.loads(engine.get_entity_by_record_id(
    'CA-CONTRACTORS', '816198', flags=F.SZ_ENTITY_DEFAULT_FLAGS))['RESOLVED_ENTITY']

print(f"{briten['ENTITY_NAME']}  ({len(briten['RECORDS'])} records)\n")
for family in ('NAME', 'ADDRESS', 'PHONE'):
    print(f"{family}:")
    for v in briten['FEATURES'].get(family, []):
        print(f"   {v['FEAT_DESC']}")

how = json.loads(engine.how_entity_by_entity_id(
    briten['ENTITY_ID'], flags=F.SZ_HOW_ENTITY_DEFAULT_FLAGS))
print("\nsteps:", [s['MATCH_INFO']['MATCH_KEY']
                   for s in how['HOW_RESULTS']['RESOLUTION_STEPS']])

BRITEN FIRE SERVICE INC  (3 records)

NAME:
   BRITEN FIRE SERVICE INC
ADDRESS:
   240 FLOURNOY STREET SAN FRANCISCO CA 94112
   5538 3RD ST, SAN FRANCISCO, CA 94124-2607
PHONE:
   (415) 713 5115

steps: ['+NAME+ADDRESS', '+NAME+PHONE']

## A slightly harder example

Give this a run and you will see that we have two entities at _nearly_ the same address and with _nearly_ the same names with the same filing dates.  And they are not merged.

In [26]:
a = json.loads(engine.get_entity_by_record_id(
    'CA-SOS-FILINGS', 'B20260322293', flags=F.SZ_ENTITY_DEFAULT_FLAGS))['RESOLVED_ENTITY']
b = json.loads(engine.get_entity_by_record_id(
    'CA-SOS-FILINGS', 'B20260322300', flags=F.SZ_ENTITY_DEFAULT_FLAGS))['RESOLVED_ENTITY']

for e in (a, b):
    print(f"entity {e['ENTITY_ID']}: {e['ENTITY_NAME']}  ({len(e['RECORDS'])} records)")
    for n in e['FEATURES']['NAME']:
        print(f"    name     {n['FEAT_DESC']}")
    print(f"    address  {e['FEATURES']['ADDRESS'][0]['FEAT_DESC']}")
    print(f"    filed    {e['FEATURES']['REGISTRATION_DATE'][0]['FEAT_DESC']}")
    print()

entity 400130: 1617-A Chapala Street LLC  (2 records)
    name     1617-A Chapala Street LLC
    name     1621-A Chapala Street LLC
    address  461 SAN YSIDRO ROAD MONTECITO CA 93108 United States
    filed    2026-07-13

entity 400131: 1617-B Chapala Street LLC  (2 records)
    name     1617-B Chapala Street LLC
    name     1621-B Chapala Street LLC
    address  461 SAN YSIDRO ROAD MONTECITO CA 93108 United States
    filed    2026-07-13

###  This cell shows why...

In [27]:
why = json.loads(engine.why_entities(
    a['ENTITY_ID'], b['ENTITY_ID'], flags=F.SZ_WHY_ENTITIES_DEFAULT_FLAGS))
info = why['WHY_RESULTS'][0]['MATCH_INFO']

print(f"{info['WHY_KEY']}   ->   {info['MATCH_LEVEL_CODE']}\n")
for family, scores in info['FEATURE_SCORES'].items():
    s = scores[0]
    print(f"  {family:<20} {s['SCORE_BUCKET']}")

+ADDRESS+REGISTRATION_DATE   ->   POSSIBLY_RELATED

  ADDRESS              SAME
  NAME                 PLAUSIBLE
  RECORD_TYPE          SAME
  REGISTRATION_DATE    SAME

## What actually happened

Someone at the address of 461 SAN YSIDRO ROAD MONTECITO set up per-unit LLCs at one address on one day.  They likely bought a couple of buildings that had multiple units and created a different LLC for each unit in order to rent them.  Merging them would destroy the only thing that matters about them.  A dedup script tuned to catch these name variants would almost certainly collapse these four into one, which is why **"just use fuzzy matching" isn't an answer.**

In [28]:
print(json.dumps(why, indent=2))

{
  "WHY_RESULTS": [
    {
      "ENTITY_ID": 400130,
      "ENTITY_ID_2": 400131,
      "MATCH_INFO": {
        "WHY_KEY": "+ADDRESS+REGISTRATION_DATE",
        "WHY_ERRULE_CODE": "SFF",
        "MATCH_LEVEL_CODE": "POSSIBLY_RELATED",
        "CANDIDATE_KEYS": {
          "ADDR_KEY": [
            {
              "FEAT_ID": 302032,
              "FEAT_DESC": "461|SN ASTR||MNTST"
            },
            {
              "FEAT_ID": 302033,
              "FEAT_DESC": "461|SN ASTR||93108"
            }
          ],
          "NAMEADDR_KEY": [
            {
              "FEAT_ID": 404710,
              "FEAT_DESC": "STRT|XPL|ADDR_KEY.EXPRESSION=461|SN ASTR||MNTST"
            },
            {
              "FEAT_ID": 404715,
              "FEAT_DESC": "STRT|XPL|ADDR_KEY.EXPRESSION=461|SN ASTR||93108"
            }
          ],
          "NAMEDATE_KEY": [
            {
              "FEAT_ID": 404723,
              "FEAT_DESC": "STRT|XPL|REGISTRATION_DATE=21307"
            },
            {
              "FEAT_ID": 404725,
              "FEAT_DESC": "STRT|XPL|REGISTRATION_DATE.MMYY_HASH=0726"
            },
            {
              "FEAT_ID": 404726,
              "FEAT_DESC": "STRT|XPL|REGISTRATION_DATE.MMDD_HASH=1307"
            }
          ],
          "NAMEREGION_KEY": [
            {
              "FEAT_ID": 404735,
              "FEAT_DESC": "STRT|XPL|ADDRESS.CITY_STD=MNTST"
            },
            {
              "FEAT_ID": 404736,
              "FEAT_DESC": "STRT|XPL|POST=93108"
            }
          ]
        },
        "FEATURE_SCORES": {
          "ADDRESS": [
            {
              "INBOUND_FEAT_ID": 404706,
              "INBOUND_FEAT_DESC": "461 SAN YSIDRO ROAD MONTECITO CA 93108 United States",
              "INBOUND_FEAT_USAGE_TYPE": "BUSINESS",
              "CANDIDATE_FEAT_ID": 404706,
              "CANDIDATE_FEAT_DESC": "461 SAN YSIDRO ROAD MONTECITO CA 93108 United States",
              "CANDIDATE_FEAT_USAGE_TYPE": "BUSINESS",
              "SCORE": 100,
              "ADDITIONAL_SCORES": {
                "FULL_SCORE": 100
              },
              "SCORE_BUCKET": "SAME",
              "SCORE_BEHAVIOR": "FFE"
            }
          ],
          "NAME": [
            {
              "INBOUND_FEAT_ID": 404705,
              "INBOUND_FEAT_DESC": "1617-A Chapala Street LLC",
              "CANDIDATE_FEAT_ID": 404737,
              "CANDIDATE_FEAT_DESC": "1617-B Chapala Street LLC",
              "SCORE": 75,
              "ADDITIONAL_SCORES": {
                "GNR_FN": 75,
                "GNR_SN": -1,
                "GNR_GN": -1,
                "GENERATION_MATCH": -1,
                "GNR_ON": 75
              },
              "SCORE_BUCKET": "PLAUSIBLE",
              "SCORE_BEHAVIOR": "NAME"
            }
          ],
          "RECORD_TYPE": [
            {
              "INBOUND_FEAT_ID": 6,
              "INBOUND_FEAT_DESC": "ORGANIZATION",
              "CANDIDATE_FEAT_ID": 6,
              "CANDIDATE_FEAT_DESC": "ORGANIZATION",
              "SCORE": 100,
              "ADDITIONAL_SCORES": {
                "FULL_SCORE": 100
              },
              "SCORE_BUCKET": "SAME",
              "SCORE_BEHAVIOR": "FVME"
            }
          ],
          "REGISTRATION_DATE": [
            {
              "INBOUND_FEAT_ID": 400211,
              "INBOUND_FEAT_DESC": "2026-07-13",
              "CANDIDATE_FEAT_ID": 400211,
              "CANDIDATE_FEAT_DESC": "2026-07-13",
              "SCORE": 100,
              "ADDITIONAL_SCORES": {
                "FULL_SCORE": 100
              },
              "SCORE_BUCKET": "SAME",
              "SCORE_BEHAVIOR": "FMES"
            }
          ]
        },
        "DISCLOSED_RELATIONS": {}
      }
    }
  ],
  "ENTITIES": [
    {
      "RESOLVED_ENTITY": {
        "ENTITY_ID": 400130
      }
    },
    {
      "RESOLVED_ENTITY": {
        "ENTITY_ID": 400131
      }
    }
  ]
}

## Reading a Resolution Step

The `how` output nests deeply, so this works through it in pieces: the shape of the steps first, then one whole step, then just the evidence for that step, then the end state.

In [29]:
how = json.loads(engine.how_entity_by_entity_id(
    1354, flags=F.SZ_HOW_ENTITY_DEFAULT_FLAGS))['HOW_RESULTS']

# 1. the shape - which steps exist and what drove each
for s in how['RESOLUTION_STEPS']:
    print(s['STEP'], s['MATCH_INFO']['MATCH_KEY'], s['MATCH_INFO']['ERRULE_CODE'])

# 2. one whole step, readable at ~3K chars
print(json.dumps(how['RESOLUTION_STEPS'][1], indent=2))

# 3. just the evidence for that step
print(json.dumps(how['RESOLUTION_STEPS'][1]['MATCH_INFO']['FEATURE_SCORES'], indent=2))

# 4. the end state - small, prints fine
print(json.dumps(how['FINAL_STATE'], indent=2))

1 +NAME+ADDRESS CNAME_CFF_CEXCL
2 +LIKELY_NAME+ADDRESS+PHONE MFF_LNAME_CEXCL
3 +NAME+ADDRESS CNAME_CFF_CEXCL
4 +NAME+ADDRESS CNAME_CFF_CEXCL
5 +LIKELY_NAME+ADDRESS+PHONE MFF_LNAME_CEXCL
6 +LIKELY_NAME+ADDRESS+PHONE MFF_LNAME_CEXCL
7 +NAME+ADDRESS+PHONE MFF_LNAME_CEXCL
8 +LIKELY_NAME+ADDRESS+PHONE MFF_LNAME_CEXCL
9 +LIKELY_NAME+ADDRESS+PHONE MFF_LNAME_CEXCL
10 +LIKELY_NAME+ADDRESS+PHONE MFF_LNAME_CEXCL
11 +LIKELY_NAME+ADDRESS+PHONE MFF_LNAME_CEXCL
12 +LIKELY_NAME+ADDRESS+PHONE MFF_LNAME_CEXCL
{
  "STEP": 2,
  "VIRTUAL_ENTITY_1": {
    "VIRTUAL_ENTITY_ID": "V600601",
    "MEMBER_RECORDS": [
      {
        "INTERNAL_ID": 600601,
        "RECORDS": [
          {
            "DATA_SOURCE": "CA-CONTRACTORS",
            "RECORD_ID": "1078219"
          }
        ]
      }
    ]
  },
  "VIRTUAL_ENTITY_2": {
    "VIRTUAL_ENTITY_ID": "V600740",
    "MEMBER_RECORDS": [
      {
        "INTERNAL_ID": 600740,
        "RECORDS": [
          {
            "DATA_SOURCE": "CA-CONTRACTORS",
            "RECORD_ID": "1093103"
          }
        ]
      }
    ]
  },
  "INBOUND_VIRTUAL_ENTITY_ID": "V600601",
  "RESULT_VIRTUAL_ENTITY_ID": "V600601-S2",
  "MATCH_INFO": {
    "MATCH_KEY": "+LIKELY_NAME+ADDRESS+PHONE",
    "ERRULE_CODE": "MFF_LNAME_CEXCL",
    "CANDIDATE_KEYS": {
      "ADDR_KEY": [
        {
          "FEAT_ID": 22395,
          "FEAT_DESC": "11555|TPLN||TPLN"
        },
        {
          "FEAT_ID": 22396,
          "FEAT_DESC": "11555|TPLN||94568"
        }
      ],
      "NAMEADDR_KEY": [
        {
          "FEAT_ID": 22397,
          "FEAT_DESC": "KNSTRKXN|TSLF|ADDR_KEY.EXPRESSION=11555|TPLN||94568"
        },
        {
          "FEAT_ID": 22399,
          "FEAT_DESC": "KNSTRKXN|KTS|ADDR_KEY.EXPRESSION=11555|TPLN||94568"
        },
        {
          "FEAT_ID": 22401,
          "FEAT_DESC": "KNSTRKXN|KTS|ADDR_KEY.EXPRESSION=11555|TPLN||TPLN"
        },
        {
          "FEAT_ID": 22402,
          "FEAT_DESC": "KNSTRKXN|TSLF|ADDR_KEY.EXPRESSION=11555|TPLN||TPLN"
        },
        {
          "FEAT_ID": 22403,
          "FEAT_DESC": "KTS|TSLF|ADDR_KEY.EXPRESSION=11555|TPLN||TPLN"
        },
        {
          "FEAT_ID": 22404,
          "FEAT_DESC": "KTS|TSLF|ADDR_KEY.EXPRESSION=11555|TPLN||94568"
        }
      ],
      "NAMEPHONE_KEY": [
        {
          "FEAT_ID": 813637,
          "FEAT_DESC": "KNSTRKXN|TSLF|PHONE.PHONE_LAST_5=99220"
        },
        {
          "FEAT_ID": 813638,
          "FEAT_DESC": "KTS|TSLF|PHONE.PHONE_LAST_5=99220"
        },
        {
          "FEAT_ID": 813640,
          "FEAT_DESC": "KNSTRKXN|KTS|PHONE.PHONE_LAST_5=99220"
        }
      ],
      "NAMEREGION_KEY": [
        {
          "FEAT_ID": 22405,
          "FEAT_DESC": "KNSTRKXN|TSLF|POST=94568"
        },
        {
          "FEAT_ID": 22406,
          "FEAT_DESC": "KTS|TSLF|ADDRESS.CITY_STD=TPLN"
        },
        {
          "FEAT_ID": 22407,
          "FEAT_DESC": "KNSTRKXN|KTS|POST=94568"
        },
        {
          "FEAT_ID": 22408,
          "FEAT_DESC": "KTS|TSLF|POST=94568"
        },
        {
          "FEAT_ID": 22409,
          "FEAT_DESC": "KNSTRKXN|KTS|ADDRESS.CITY_STD=TPLN"
        },
        {
          "FEAT_ID": 22410,
          "FEAT_DESC": "KNSTRKXN|TSLF|ADDRESS.CITY_STD=TPLN"
        }
      ],
      "PHONE_KEY": [
        {
          "FEAT_ID": 812041,
          "FEAT_DESC": "9258299220"
        }
      ]
    },
    "FEATURE_SCORES": {
      "ADDRESS": [
        {
          "INBOUND_FEAT_ID": 813636,
          "INBOUND_FEAT_DESC": "11555 DUBLIN BOULEVARD DUBLIN CA 94568",
          "INBOUND_FEAT_USAGE_TYPE": "BUSINESS",
          "CANDIDATE_FEAT_ID": 811846,
          "CANDIDATE_FEAT_DESC": "11555 DUBLIN BLVD DUBLIN CA 94568",
          "CANDIDATE_FEAT_USAGE_TYPE": "BUSINESS",
          "SCORE": 99,
          "ADDITIONAL_SCORES": {
            "FULL_SCORE": 99
          },
          "SCORE_BUCKET": "SAME",
          "SCORE_BEHAVIOR": "FFE"
        }
      ],
      "NAME": [
        {
          "INBOUND_FEAT_ID": 22392,
          "INBOUND_FEAT_DESC": "DESILVA GATES CONSTRUCTION LLC",
          "CANDIDATE_FEAT_ID": 816579,
          "CANDIDATE_FEAT_DESC": "DESILVA GATES CONSTRUCTION LLC - MCM A JOINT VENTURE",
          "SCORE": 84,
          "ADDITIONAL_SCORES": {
            "GNR_FN": 84,
            "GNR_SN": -1,
            "GNR_GN": -1,
            "GENERATION_MATCH": -1,
            "GNR_ON": 84
          },
          "SCORE_BUCKET": "LIKELY",
          "SCORE_BEHAVIOR": "NAME"
        }
      ],
      "PHONE": [
        {
          "INBOUND_FEAT_ID": 812039,
          "INBOUND_FEAT_DESC": "(925) 829 9220",
          "INBOUND_FEAT_USAGE_TYPE": "WORK",
          "CANDIDATE_FEAT_ID": 812039,
          "CANDIDATE_FEAT_DESC": "(925) 829 9220",
          "CANDIDATE_FEAT_USAGE_TYPE": "WORK",
          "SCORE": 100,
          "ADDITIONAL_SCORES": {
            "FULL_SCORE": 100
          },
          "SCORE_BUCKET": "SAME",
          "SCORE_BEHAVIOR": "FF"
        }
      ],
      "RECORD_TYPE": [
        {
          "INBOUND_FEAT_ID": 6,
          "INBOUND_FEAT_DESC": "ORGANIZATION",
          "CANDIDATE_FEAT_ID": 6,
          "CANDIDATE_FEAT_DESC": "ORGANIZATION",
          "SCORE": 100,
          "ADDITIONAL_SCORES": {
            "FULL_SCORE": 100
          },
          "SCORE_BUCKET": "SAME",
          "SCORE_BEHAVIOR": "FVME"
        }
      ]
    }
  }
}
{
  "ADDRESS": [
    {
      "INBOUND_FEAT_ID": 813636,
      "INBOUND_FEAT_DESC": "11555 DUBLIN BOULEVARD DUBLIN CA 94568",
      "INBOUND_FEAT_USAGE_TYPE": "BUSINESS",
      "CANDIDATE_FEAT_ID": 811846,
      "CANDIDATE_FEAT_DESC": "11555 DUBLIN BLVD DUBLIN CA 94568",
      "CANDIDATE_FEAT_USAGE_TYPE": "BUSINESS",
      "SCORE": 99,
      "ADDITIONAL_SCORES": {
        "FULL_SCORE": 99
      },
      "SCORE_BUCKET": "SAME",
      "SCORE_BEHAVIOR": "FFE"
    }
  ],
  "NAME": [
    {
      "INBOUND_FEAT_ID": 22392,
      "INBOUND_FEAT_DESC": "DESILVA GATES CONSTRUCTION LLC",
      "CANDIDATE_FEAT_ID": 816579,
      "CANDIDATE_FEAT_DESC": "DESILVA GATES CONSTRUCTION LLC - MCM A JOINT VENTURE",
      "SCORE": 84,
      "ADDITIONAL_SCORES": {
        "GNR_FN": 84,
        "GNR_SN": -1,
        "GNR_GN": -1,
        "GENERATION_MATCH": -1,
        "GNR_ON": 84
      },
      "SCORE_BUCKET": "LIKELY",
      "SCORE_BEHAVIOR": "NAME"
    }
  ],
  "PHONE": [
    {
      "INBOUND_FEAT_ID": 812039,
      "INBOUND_FEAT_DESC": "(925) 829 9220",
      "INBOUND_FEAT_USAGE_TYPE": "WORK",
      "CANDIDATE_FEAT_ID": 812039,
      "CANDIDATE_FEAT_DESC": "(925) 829 9220",
      "CANDIDATE_FEAT_USAGE_TYPE": "WORK",
      "SCORE": 100,
      "ADDITIONAL_SCORES": {
        "FULL_SCORE": 100
      },
      "SCORE_BUCKET": "SAME",
      "SCORE_BEHAVIOR": "FF"
    }
  ],
  "RECORD_TYPE": [
    {
      "INBOUND_FEAT_ID": 6,
      "INBOUND_FEAT_DESC": "ORGANIZATION",
      "CANDIDATE_FEAT_ID": 6,
      "CANDIDATE_FEAT_DESC": "ORGANIZATION",
      "SCORE": 100,
      "ADDITIONAL_SCORES": {
        "FULL_SCORE": 100
      },
      "SCORE_BUCKET": "SAME",
      "SCORE_BEHAVIOR": "FVME"
    }
  ]
}
{
  "NEED_REEVALUATION": 0,
  "VIRTUAL_ENTITIES": [
    {
      "VIRTUAL_ENTITY_ID": "V1354-S12",
      "MEMBER_RECORDS": [
        {
          "INTERNAL_ID": 1354,
          "RECORDS": [
            {
              "DATA_SOURCE": "BURLINGAME",
              "RECORD_ID": "20501298"
            }
          ]
        },
        {
          "INTERNAL_ID": 600521,
          "RECORDS": [
            {
              "DATA_SOURCE": "CA-CONTRACTORS",
              "RECORD_ID": "1068502"
            }
          ]
        },
        {
          "INTERNAL_ID": 600526,
          "RECORDS": [
            {
              "DATA_SOURCE": "CA-CONTRACTORS",
              "RECORD_ID": "1069062"
            }
          ]
        },
        {
          "INTERNAL_ID": 600601,
          "RECORDS": [
            {
              "DATA_SOURCE": "CA-CONTRACTORS",
              "RECORD_ID": "1078219"
            }
          ]
        },
        {
          "INTERNAL_ID": 600686,
          "RECORDS": [
            {
              "DATA_SOURCE": "CA-CONTRACTORS",
              "RECORD_ID": "1087418"
            }
          ]
        },
        {
          "INTERNAL_ID": 600731,
          "RECORDS": [
            {
              "DATA_SOURCE": "CA-CONTRACTORS",
              "RECORD_ID": "1092458"
            }
          ]
        },
        {
          "INTERNAL_ID": 600740,
          "RECORDS": [
            {
              "DATA_SOURCE": "CA-CONTRACTORS",
              "RECORD_ID": "1093103"
            }
          ]
        },
        {
          "INTERNAL_ID": 600815,
          "RECORDS": [
            {
              "DATA_SOURCE": "CA-CONTRACTORS",
              "RECORD_ID": "1100766"
            }
          ]
        },
        {
          "INTERNAL_ID": 600837,
          "RECORDS": [
            {
              "DATA_SOURCE": "CA-CONTRACTORS",
              "RECORD_ID": "1103207"
            }
          ]
        },
        {
          "INTERNAL_ID": 601043,
          "RECORDS": [
            {
              "DATA_SOURCE": "CA-CONTRACTORS",
              "RECORD_ID": "1125855"
            }
          ]
        },
        {
          "INTERNAL_ID": 601150,
          "RECORDS": [
            {
              "DATA_SOURCE": "CA-CONTRACTORS",
              "RECORD_ID": "1136862"
            }
          ]
        },
        {
          "INTERNAL_ID": 601359,
          "RECORDS": [
            {
              "DATA_SOURCE": "CA-CONTRACTORS",
              "RECORD_ID": "1156955"
            }
          ]
        },
        {
          "INTERNAL_ID": 602109,
          "RECORDS": [
            {
              "DATA_SOURCE": "CA-CONTRACTORS",
              "RECORD_ID": "704195"
            }
          ]
        }
      ]
    }
  ]
}

## The Same Step, Trimmed

`CANDIDATE_KEYS` lists every value Senzing considered as a way of finding this record.  It is long and rarely what you want to read, so this prints the step without it.

In [30]:
step = {k: v for k, v in how['RESOLUTION_STEPS'][1].items() if k != 'MATCH_INFO'}
step['MATCH_INFO'] = {k: v for k, v in how['RESOLUTION_STEPS'][1]['MATCH_INFO'].items()
                      if k != 'CANDIDATE_KEYS'}
print(json.dumps(step, indent=2))

{
  "STEP": 2,
  "VIRTUAL_ENTITY_1": {
    "VIRTUAL_ENTITY_ID": "V600601",
    "MEMBER_RECORDS": [
      {
        "INTERNAL_ID": 600601,
        "RECORDS": [
          {
            "DATA_SOURCE": "CA-CONTRACTORS",
            "RECORD_ID": "1078219"
          }
        ]
      }
    ]
  },
  "VIRTUAL_ENTITY_2": {
    "VIRTUAL_ENTITY_ID": "V600740",
    "MEMBER_RECORDS": [
      {
        "INTERNAL_ID": 600740,
        "RECORDS": [
          {
            "DATA_SOURCE": "CA-CONTRACTORS",
            "RECORD_ID": "1093103"
          }
        ]
      }
    ]
  },
  "INBOUND_VIRTUAL_ENTITY_ID": "V600601",
  "RESULT_VIRTUAL_ENTITY_ID": "V600601-S2",
  "MATCH_INFO": {
    "MATCH_KEY": "+LIKELY_NAME+ADDRESS+PHONE",
    "ERRULE_CODE": "MFF_LNAME_CEXCL",
    "FEATURE_SCORES": {
      "ADDRESS": [
        {
          "INBOUND_FEAT_ID": 813636,
          "INBOUND_FEAT_DESC": "11555 DUBLIN BOULEVARD DUBLIN CA 94568",
          "INBOUND_FEAT_USAGE_TYPE": "BUSINESS",
          "CANDIDATE_FEAT_ID": 811846,
          "CANDIDATE_FEAT_DESC": "11555 DUBLIN BLVD DUBLIN CA 94568",
          "CANDIDATE_FEAT_USAGE_TYPE": "BUSINESS",
          "SCORE": 99,
          "ADDITIONAL_SCORES": {
            "FULL_SCORE": 99
          },
          "SCORE_BUCKET": "SAME",
          "SCORE_BEHAVIOR": "FFE"
        }
      ],
      "NAME": [
        {
          "INBOUND_FEAT_ID": 22392,
          "INBOUND_FEAT_DESC": "DESILVA GATES CONSTRUCTION LLC",
          "CANDIDATE_FEAT_ID": 816579,
          "CANDIDATE_FEAT_DESC": "DESILVA GATES CONSTRUCTION LLC - MCM A JOINT VENTURE",
          "SCORE": 84,
          "ADDITIONAL_SCORES": {
            "GNR_FN": 84,
            "GNR_SN": -1,
            "GNR_GN": -1,
            "GENERATION_MATCH": -1,
            "GNR_ON": 84
          },
          "SCORE_BUCKET": "LIKELY",
          "SCORE_BEHAVIOR": "NAME"
        }
      ],
      "PHONE": [
        {
          "INBOUND_FEAT_ID": 812039,
          "INBOUND_FEAT_DESC": "(925) 829 9220",
          "INBOUND_FEAT_USAGE_TYPE": "WORK",
          "CANDIDATE_FEAT_ID": 812039,
          "CANDIDATE_FEAT_DESC": "(925) 829 9220",
          "CANDIDATE_FEAT_USAGE_TYPE": "WORK",
          "SCORE": 100,
          "ADDITIONAL_SCORES": {
            "FULL_SCORE": 100
          },
          "SCORE_BUCKET": "SAME",
          "SCORE_BEHAVIOR": "FF"
        }
      ],
      "RECORD_TYPE": [
        {
          "INBOUND_FEAT_ID": 6,
          "INBOUND_FEAT_DESC": "ORGANIZATION",
          "CANDIDATE_FEAT_ID": 6,
          "CANDIDATE_FEAT_DESC": "ORGANIZATION",
          "SCORE": 100,
          "ADDITIONAL_SCORES": {
            "FULL_SCORE": 100
          },
          "SCORE_BUCKET": "SAME",
          "SCORE_BEHAVIOR": "FVME"
        }
      ]
    }
  }
}

## People and Companies

Records carry a `RECORD_TYPE`, and Senzing will not merge a person with an organization no matter how much else they share.  Without it, every business registered to a home address would absorb the person living there.

In [31]:
types = pd.read_sql("""
    SELECT dsrc_id,
           count(*) FILTER (WHERE json_data::jsonb->'FEATURES' @> '[{"RECORD_TYPE":"PERSON"}]')       AS persons,
           count(*) FILTER (WHERE json_data::jsonb->'FEATURES' @> '[{"RECORD_TYPE":"ORGANIZATION"}]') AS orgs
    FROM dsrc_record GROUP BY dsrc_id ORDER BY 2 DESC
""", db)
types['data_source'] = types.dsrc_id.map(names)
print(types[['data_source', 'persons', 'orgs']].to_string(index=False))

            data_source  persons  orgs
CA-CONTRACTOR-PERSONNEL    10033   182
      CA-SOS-PRINCIPALS     5523   178
          CA-SOS-AGENTS     5039  2382
         CA-CONTRACTORS        0  3274
          ABC-NONRETAIL        0    19
         CA-SOS-FILINGS        0  7801
             ABC-RETAIL        0   201
             BURLINGAME        0  4781

## A Person Across Several Companies

Registered agents and corporate officers appear once per company they are involved with.  Resolution collects those appearances into one person, which is what makes it possible to ask who is connected to whom.

In [32]:
person = json.loads(engine.get_entity_by_record_id(
    'CA-SOS-AGENTS', 'B20260328234', flags=F.SZ_ENTITY_DEFAULT_FLAGS))['RESOLVED_ENTITY']

print(f"entity {person['ENTITY_ID']}: {person['ENTITY_NAME']}  ({len(person['RECORDS'])} records)")
print(f"  type:    {person['FEATURES']['RECORD_TYPE'][0]['FEAT_DESC']}")
print(f"  name:    {[n['FEAT_DESC'] for n in person['FEATURES']['NAME']]}")
print(f"  address: {person['FEATURES']['ADDRESS'][0]['FEAT_DESC']}")

entity 302070: ZHONGHAO CAO  (10 records)
  type:    PERSON
  name:    ['Zhonghao Cao']
  address: 828 W EL REPETTO DR MONTEREY PARK CA 91754 UNITED STATES

In [33]:
print(f"{person['ENTITY_NAME']} appears as:\n")
for r in person['RECORDS']:
    rec = json.loads(engine.get_record(r['DATA_SOURCE'], r['RECORD_ID']))['JSON_DATA']
    company = rec.get('COMPANY_NAME') or rec.get('REPRESENTS_COMPANY') or '?'
    role = rec.get('POSITION_TYPE') or rec.get('AGENT_TYPE') or ''
    print(f"  {company[:34]:<34} {role}")

ZHONGHAO CAO appears as:

  ZHC CONSTRUCTION INC               Individual Agent
  HE WINDOW INC                      Individual Agent
  ZHC CONSTRUCTION INC               Chief Executive Officer
  ZHC CONSTRUCTION INC               Chief Financial Officer
  ZHC CONSTRUCTION INC               Secretary
  ZHC CONSTRUCTION INC               Director
  HE WINDOW INC                      Chief Executive Officer
  HE WINDOW INC                      Chief Financial Officer
  HE WINDOW INC                      Secretary
  HE WINDOW INC                      Director

## The busiest people in the data

Because we have data showing personnel as they appear across companies, we can look at something fun, like how many companies they are associated with.  Some are genuinely prolific officers, and some are professional registered agent firms recorded as though they were a person.

In [34]:
busiest = pd.read_sql("""
    SELECT k.res_ent_id AS entity_id,
           count(DISTINCT COALESCE(d.json_data::jsonb->>'COMPANY_NAME',
                                   d.json_data::jsonb->>'REPRESENTS_COMPANY')) AS companies,
           count(*) AS records
    FROM dsrc_record d
    JOIN obs_ent o      ON o.dsrc_id = d.dsrc_id AND o.ent_src_key = d.ent_src_key
    JOIN res_ent_okey k ON k.obs_ent_id = o.obs_ent_id
    WHERE d.json_data::jsonb->'FEATURES' @> '[{"RECORD_TYPE":"PERSON"}]'
    GROUP BY 1
    HAVING count(DISTINCT COALESCE(d.json_data::jsonb->>'COMPANY_NAME',
                                   d.json_data::jsonb->>'REPRESENTS_COMPANY')) > 1
    ORDER BY 2 DESC LIMIT 10
""", db)

for row in busiest.itertuples():
    e = json.loads(engine.get_entity_by_entity_id(row.entity_id))['RESOLVED_ENTITY']
    print(f"  {e['ENTITY_NAME'][:36]:<36} {row.companies} companies, {row.records} records")

  Shelene Nordstrom-Vaka               20 companies, 20 records
  Bhanu Partap Rana                    11 companies, 11 records
  SUSANNA WATT                         9 companies, 9 records
  Michael Kelly                        8 companies, 8 records
  David Fradin                         8 companies, 8 records
  KRISTINA PETROSYAN                   5 companies, 5 records
  Rachel Novak Siegel                  5 companies, 7 records
  Ishkhan Shahazizyan                  5 companies, 5 records
  Alejandro Duran                      4 companies, 4 records
  JAY K PAUL                           4 companies, 4 records

## Businesses at the Same Coordinates

Grouping by rounded latitude and longitude shows how many businesses share a location.  Some of these are real office buildings, and some are addresses that failed to geocode and landed together by accident.

In [35]:
pd.read_sql("""
    SELECT round(latitude::numeric, 5)  AS lat,
           round(longitude::numeric, 5) AS lon,
           count(DISTINCT entity_id)    AS businesses,
           min(street)                  AS example_address
    FROM workshop.entity_geo
    GROUP BY 1, 2 ORDER BY 3 DESC LIMIT 10
""", db)

        lat        lon  businesses        example_address
0  37.58992 -122.34032         118       533 AIRPORT BLVD
1  37.57830 -122.34867          71    1354 BURLINGAME AVE
2  37.59447 -122.38618          69          1533 PLAZA LN
3  37.57712 -122.34910          65    1400 BURLINGAME AVE
4  37.57898 -122.34570          63    1101 BURLINGAME AVE
5  37.59940 -122.36944          49      1633 BAYSHORE 136
6  37.57780 -122.34613          46  1220 HOWARD AVE # 216
7  37.58202 -122.34187          45     850 BURLINGAME AVE
8  37.57662 -122.34656          43        1321 HOWARD AVE
9  37.57982 -122.34675          41    1202 BURLINGAME AVE

## Finding the Conference Hotel

Everything from here on uses the Hyatt Regency San Francisco Airport as a starting point, so the next few cells locate it three ways: by search, by raw record, and by entity ID.  We will use that entity ID in the future notebooks, so let's get it now...

In [36]:
results = json.loads(engine.search_by_attributes(
    json.dumps({'NAME_ORG': 'HYATT REGENCY SAN FRANCISCO AIRPORT'})))

for hit in results.get('RESOLVED_ENTITIES', []):
    e = hit['ENTITY']['RESOLVED_ENTITY']
    print(f"entity {e['ENTITY_ID']}: {e['ENTITY_NAME']}  match={hit['MATCH_INFO']['MATCH_KEY']}")

entity 2120: HYATT REGENCY SAN FRANCISCO AIRPORT  match=+NAME

In [37]:
HYATT = 2120

e = json.loads(engine.get_entity_by_entity_id(
    HYATT, flags=F.SZ_ENTITY_DEFAULT_FLAGS))['RESOLVED_ENTITY']

print(f"{e['ENTITY_NAME']}  ({len(e['RECORDS'])} records)")
for r in e['RECORDS']:
    print(f"   {r['DATA_SOURCE']:<14} {r['RECORD_ID']}")
print(f"   {e['FEATURES']['ADDRESS'][0]['FEAT_DESC']}")

HYATT REGENCY SAN FRANCISCO AIRPORT  (3 records)
   BURLINGAME     20500020
   ABC-RETAIL     220571-47
   ABC-RETAIL     220571-58
   1333 BAYSHORE HWY, BURLINGAME, CA 94010-1886

## Why the Hotel's Records Merged

`why_records` is the record level version of `why_entities`.  It answers why these two specific records, one city licence and one liquor licence, were treated as the same business.

In [38]:
why = json.loads(engine.why_records(
    'BURLINGAME', '20500020', 'ABC-RETAIL', '220571-47'))
info = why['WHY_RESULTS'][0]['MATCH_INFO']

print(f"{info['WHY_KEY']}  ->  {info['MATCH_LEVEL_CODE']}")
for family, scores in info['FEATURE_SCORES'].items():
    print(f"   {family:<14} {scores[0]['SCORE_BUCKET']}")

+NAME+ADDRESS  ->  RESOLVED
   ADDRESS        SAME
   NAME           SAME
   RECORD_TYPE    SAME

## What the Hotel Is Related To

The entities Senzing connected to the hotel but kept separate.  Most of these share its address, which is to say they are tenants in the same building.

In [39]:
d = json.loads(engine.get_entity_by_entity_id(HYATT, flags=F.SZ_ENTITY_DEFAULT_FLAGS))

for r in d['RELATED_ENTITIES']:
    print(f"  {r['ENTITY_NAME'][:42]:<42} {r['MATCH_LEVEL_CODE']}  {r['MATCH_KEY']}")

  CURTIN CONVENTION & EXPOSITION SERVICE     POSSIBLY_RELATED  +ADDRESS
  ENCORE GROUP USA LLC                       POSSIBLY_RELATED  +ADDRESS
  HALLMARK MARKETING CORPORATION             POSSIBLY_RELATED  +ADDRESS
  IRON MOUNTAIN                              POSSIBLY_RELATED  +ADDRESS
  TRAVEL TRADERS #698                        POSSIBLY_RELATED  +ADDRESS

## The Network Around the Hotel

`find_network_by_entity_id` walks the relationships outward from one entity.  This is ER producing graph structure directly, before we build anything ourselves in NetworkX.

In [40]:
net = json.loads(engine.find_network_by_entity_id(
    [HYATT], 2, 1, 10, flags=F.SZ_FIND_NETWORK_DEFAULT_FLAGS))

print(f"{len(net['ENTITIES'])} entities in the network\n")
for e in net['ENTITIES']:
    r = e['RESOLVED_ENTITY']
    print(f"  {r['ENTITY_ID']:>6}  {r.get('ENTITY_NAME','')[:44]}")

6 entities in the network

    1259  CURTIN CONVENTION & EXPOSITION SERVICE
    1561  ENCORE GROUP USA LLC
    1993  HALLMARK MARKETING CORPORATION
    2120  HYATT REGENCY SAN FRANCISCO AIRPORT
    2202  IRON MOUNTAIN
    4394  TRAVEL TRADERS #698

## What Is Nearby

The first query that uses the coordinates for distance rather than for display.  Senzing has no idea what nearby means, so the arithmetic happens in SQL and the entity lookups happen afterwards.

### Important note on distance calculations

For calculating distance, we are going to use the Haversine distance, which is a way to get a reasonable **straight-line distance** approximation between two GPS coordinates.  Note that when we created the geocodes, we are able to use them to get GPS coordinates.  However, these are the coordinates of the center of the H3 cell.  So there is a certain amount of error in distance that comes inherently built into this since addresses are not necessarily in the center of a cell.  Also bear in mind that two different addresses can appear in the same cell just based on cell size.

In [41]:
nearby = pd.read_sql("""
    WITH me AS (SELECT latitude la, longitude lo
                FROM workshop.entity_geo WHERE entity_id = 2120 LIMIT 1)
    SELECT DISTINCT g.entity_id, g.street,
           round((6371000*2*asin(sqrt(
               power(sin(radians(g.latitude - me.la)/2), 2) +
               cos(radians(me.la))*cos(radians(g.latitude)) *
               power(sin(radians(g.longitude - me.lo)/2), 2))))::numeric) AS metres
    FROM workshop.entity_geo g, me
    WHERE g.entity_id <> 2120 AND g.street NOT LIKE 'PO BOX%%'
    ORDER BY metres LIMIT 20
""", db)

for row in nearby.itertuples():
    e = json.loads(engine.get_entity_by_entity_id(row.entity_id))['RESOLVED_ENTITY']
    print(f"  {row.metres:>5.0f}m  {e['ENTITY_NAME'][:44]}")

      0m  CURTIN CONVENTION & EXPOSITION SERVICE
      0m  ENCORE GROUP USA LLC
      0m  HALLMARK MARKETING CORPORATION
      0m  IRON MOUNTAIN
      0m  TRAVEL TRADERS #698
    131m  B Y & S CPAS A PROFESSIONAL CORPORATION
    131m  BAY AREA SERVICE
    131m  CAL MOBILITY
    131m  E KWONG ACUPUNCTURE CLINIC
    131m  EASA ARCHITECTURE
    131m  ELIE CORP
    131m  ENERGY REAL ESTATE INC
    131m  ER STUDIO
    131m  FARHAD TAX BOOKKEEPING CONSULTING SERV
    131m  FEEDLITECH
    131m  GREEN CAB PENINSULA
    131m  GUARANTEE MORTGAGE
    131m  HABITAT
    131m  HABITAT
    131m  INTENTIONAL HEALTH

## Let's make it a little more fun!

We are going to do the same thing, but now we are going to add in that the targets must also have an ABC license.  This is the question notebook 04 will fail to answer and notebook 05 will answer properly.

In [42]:
sql = """
WITH me AS (SELECT latitude la, longitude lo
            FROM workshop.entity_geo WHERE entity_id = 2120 LIMIT 1),
abc AS (
  SELECT k.res_ent_id AS entity_id,
         string_agg(DISTINCT d.json_data::jsonb->>'LICENSE_TYPE', ',')   AS lic_types,
         string_agg(DISTINCT d.json_data::jsonb->>'LICENSE_STATUS', ',') AS status
  FROM dsrc_record d
  JOIN obs_ent o      ON o.dsrc_id = d.dsrc_id AND o.ent_src_key = d.ent_src_key
  JOIN res_ent_okey k ON k.obs_ent_id = o.obs_ent_id
  WHERE d.dsrc_id IN (1002, 1003)          -- ABC-RETAIL, ABC-NONRETAIL
  GROUP BY 1)
SELECT DISTINCT a.entity_id, g.street, a.lic_types, a.status,
   round((6371000*2*asin(sqrt(
       power(sin(radians(g.latitude - me.la)/2), 2) +
       cos(radians(me.la))*cos(radians(g.latitude)) *
       power(sin(radians(g.longitude - me.lo)/2), 2))))::numeric) AS metres
FROM abc a JOIN workshop.entity_geo g ON g.entity_id = a.entity_id, me
WHERE a.entity_id <> 2120
ORDER BY metres LIMIT 20
"""

for r in pd.read_sql(sql, db).itertuples():
    e = json.loads(engine.get_entity_by_entity_id(r.entity_id))['RESOLVED_ENTITY']
    print(f"  {r.metres:>5.0f}m (~{int(r.metres/80):>2d} min)  "
          f"{e['ENTITY_NAME'][:34]:<34} type {r.lic_types:<6} {r.street[:26]}")

    131m (~ 1 min)  MR TERIYAKI                        type 41     851 BURLWAY RD # 900
    131m (~ 1 min)  MR TERIYAKI                        type 41     851 BURLWAY RD, STE 900
    263m (~ 3 min)  MAXS OF BURLINGAME                 type 47,58  1250 BAYSHORE HWY
    355m (~ 4 min)  GRAND HARBOR SEAFOOD AND DIMSUM    type 47     1492 BAYSHORE HWY
    409m (~ 5 min)  GRAND HARBOR SEAFOOD AND DIMSUM    type 47     1492 OLD BAYSHORE HWY
    478m (~ 5 min)  LEGACY THROUGH GIVING FOUNDATION   type 17     1321 N CAROLAN AVE
    486m (~ 6 min)  BENIHANA OF TOKYO INC              type 47     1496 BAYSHORE HWY
    577m (~ 7 min)  H L PENINSULA PEARL                type 47     1590 BAYSHORE HWY
    656m (~ 8 min)  CROWNE PLAZA SAN FRANCISCO AIRPORT type 47     1177 AIRPORT BLVD
    692m (~ 8 min)  H L PENINSULA HOT POT & GRILL LLC  type 47     1600 BAYSHORE HWY
    692m (~ 8 min)  MAVERICK JACKS                     type 41,58  1190 CALIFORNIA DR
    699m (~ 8 min)  VAGABOND INN EXECUTIVE SAN FRANCIS type 70     1640 BAYSHORE HWY
    699m (~ 8 min)  VAGABOND INN EXECUTIVE SAN FRANCIS type 70     1640 OLD BAYSHORE HIGHWAY
    709m (~ 8 min)  TASTE CATERING                     type 58,83  1534 ROLLINS RD
    709m (~ 8 min)  TASTE CATERING                     type 58,83  1534 ROLLINS ROAD
    709m (~ 8 min)  INTERNATIONAL BEVERAGE             type 13     1594 ROLLINS RD
    711m (~ 8 min)  WEIMAX WINES & SPIRITS             type 42     1178 BROADWAY
    711m (~ 8 min)  YANGON                             type 41     1136 BROADWAY
    711m (~ 8 min)  SOCIETY                            type 47     1130 BROADWAY
    813m (~10 min)  MOKUTANYA                          type 41     1155 CALIFORNIA DR, UNIT G

## Conclusion

In this notebook we have gotten to see how to use the Senzing SDK to get back some basic and useful ER information.  We also saw some quick ways that we could use SQL to get some geo information back.  

**But wouldn't it be nice if we could just ask this stuff of an LLM???**